name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        # Install scrot for GUI tests
        sudo apt-get update
        sudo apt-get install scrot
    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install GUI testing dependencies
      run: |
        conda install pytest pyautogui
        # Additional dependencies for virtual display
        conda install -c conda-forge xvfbwrapper
    - name: Run GUI tests with pytest
      run: |
        xvfb-run pytest
